//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GisalSpareParts.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GisalSpareParts.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите язык.
        /// </summary>
        public static string Choose_language {
            get {
                return ResourceManager.GetString("Choose language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        public static string Администратор {
            get {
                return ResourceManager.GetString("Администратор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администрирование.
        /// </summary>
        public static string Администрирование {
            get {
                return ResourceManager.GetString("Администрирование", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активные.
        /// </summary>
        public static string Активные {
            get {
                return ResourceManager.GetString("Активные", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия.
        /// </summary>
        public static string Версия {
            get {
                return ResourceManager.GetString("Версия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        public static string Внимание {
            get {
                return ResourceManager.GetString("Внимание", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановить.
        /// </summary>
        public static string Восстановить {
            get {
                return ResourceManager.GetString("Восстановить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все фирмы.
        /// </summary>
        public static string Все_фирмы {
            get {
                return ResourceManager.GetString("Все фирмы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string Вход {
            get {
                return ResourceManager.GetString("Вход", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход в систему.
        /// </summary>
        public static string Вход_в_систему {
            get {
                return ResourceManager.GetString("Вход в систему", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотие восстановить.
        /// </summary>
        public static string Вы_действительно_хотие_восстановить {
            get {
                return ResourceManager.GetString("Вы действительно хотие восстановить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотие удалить.
        /// </summary>
        public static string Вы_действительно_хотие_удалить {
            get {
                return ResourceManager.GetString("Вы действительно хотие удалить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотие удалить из базы.
        /// </summary>
        public static string Вы_действительно_хотие_удалить_из_базы {
            get {
                return ResourceManager.GetString("Вы действительно хотие удалить из базы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотие удалить файл.
        /// </summary>
        public static string Вы_действительно_хотие_удалить_файл {
            get {
                return ResourceManager.GetString("Вы действительно хотие удалить файл", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите заказчика.
        /// </summary>
        public static string Выберите_заказчика {
            get {
                return ResourceManager.GetString("Выберите заказчика", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выгрузка.
        /// </summary>
        public static string Выгрузка {
            get {
                return ResourceManager.GetString("Выгрузка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string Выход {
            get {
                return ResourceManager.GetString("Выход", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string Да {
            get {
                return ResourceManager.GetString("Да", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные отсутствуют.
        /// </summary>
        public static string Данные_отсутствуют {
            get {
                return ResourceManager.GetString("Данные отсутствуют", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный пароль нельзя использовать.
        /// </summary>
        public static string Данный_пароль_нельзя_использовать {
            get {
                return ResourceManager.GetString("Данный пароль нельзя использовать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string Дата {
            get {
                return ResourceManager.GetString("Дата", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата заказа.
        /// </summary>
        public static string Дата_заказа {
            get {
                return ResourceManager.GetString("Дата заказа", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата исполнения заказа просрочена.
        /// </summary>
        public static string Дата_исполнения_заказа_просрочена {
            get {
                return ResourceManager.GetString("Дата исполнения заказа просрочена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата поставки.
        /// </summary>
        public static string Дата_поставки {
            get {
                return ResourceManager.GetString("Дата поставки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string Добавить {
            get {
                return ResourceManager.GetString("Добавить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление.
        /// </summary>
        public static string Добавление {
            get {
                return ResourceManager.GetString("Добавление", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Журнал изменений.
        /// </summary>
        public static string Журнал_изменений {
            get {
                return ResourceManager.GetString("Журнал изменений", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завод воды &quot;ЮНИКС&quot; в Чимкенте.
        /// </summary>
        public static string Завод_воды__ЮНИКС__в_Чимкенте {
            get {
                return ResourceManager.GetString("Завод воды \"ЮНИКС\" в Чимкенте", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завод преформ Юни Пак.
        /// </summary>
        public static string Завод_преформ_Юни_Пак {
            get {
                return ResourceManager.GetString("Завод преформ Юни Пак", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка данных.
        /// </summary>
        public static string Загрузка_данных {
            get {
                return ResourceManager.GetString("Загрузка данных", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ запчастей.
        /// </summary>
        public static string Заказ_запчастей {
            get {
                return ResourceManager.GetString("Заказ запчастей", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ исполнен и поступил заказчику.
        /// </summary>
        public static string Заказ_исполнен_и_поступил_заказчику {
            get {
                return ResourceManager.GetString("Заказ исполнен и поступил заказчику", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ исполнен с замечаниями.
        /// </summary>
        public static string Заказ_исполнен_с_замечаниями {
            get {
                return ResourceManager.GetString("Заказ исполнен с замечаниями", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ на складе Gisal.
        /// </summary>
        public static string Заказ_на_складе_Gisal {
            get {
                return ResourceManager.GetString("Заказ на складе Gisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ отгружен со склада.
        /// </summary>
        public static string Заказ_отгружен_со_склада {
            get {
                return ResourceManager.GetString("Заказ отгружен со склада", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ отменен.
        /// </summary>
        public static string Заказ_отменен {
            get {
                return ResourceManager.GetString("Заказ отменен", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ принят.
        /// </summary>
        public static string Заказ_принят {
            get {
                return ResourceManager.GetString("Заказ принят", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ размещён.
        /// </summary>
        public static string Заказ_размещён {
            get {
                return ResourceManager.GetString("Заказ размещён", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ создан.
        /// </summary>
        public static string Заказ_создан {
            get {
                return ResourceManager.GetString("Заказ создан", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ успешно восстановлен.
        /// </summary>
        public static string Заказ_успешно_восстановлен {
            get {
                return ResourceManager.GetString("Заказ успешно восстановлен", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ успешно изменен.
        /// </summary>
        public static string Заказ_успешно_изменен {
            get {
                return ResourceManager.GetString("Заказ успешно изменен", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ успешно создан.
        /// </summary>
        public static string Заказ_успешно_создан {
            get {
                return ResourceManager.GetString("Заказ успешно создан", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ успешно удален.
        /// </summary>
        public static string Заказ_успешно_удален {
            get {
                return ResourceManager.GetString("Заказ успешно удален", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ успешно удален из базы.
        /// </summary>
        public static string Заказ_успешно_удален_из_базы {
            get {
                return ResourceManager.GetString("Заказ успешно удален из базы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказчик.
        /// </summary>
        public static string Заказчик {
            get {
                return ResourceManager.GetString("Заказчик", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказы.
        /// </summary>
        public static string Заказы {
            get {
                return ResourceManager.GetString("Заказы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запчасти Gisal.
        /// </summary>
        public static string Запчасти_Gisal {
            get {
                return ResourceManager.GetString("Запчасти Gisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        public static string Изменить {
            get {
                return ResourceManager.GetString("Изменить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить пароль.
        /// </summary>
        public static string Изменить_пароль {
            get {
                return ResourceManager.GetString("Изменить пароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иметь минимум 8 символов в длину.
        /// </summary>
        public static string Иметь_минимум_8_символов_в_длину {
            get {
                return ResourceManager.GetString("Иметь минимум 8 символов в длину", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя.
        /// </summary>
        public static string Имя_пользователя {
            get {
                return ResourceManager.GetString("Имя пользователя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточка заказа.
        /// </summary>
        public static string Карточка_заказа {
            get {
                return ResourceManager.GetString("Карточка заказа", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код Gisal.
        /// </summary>
        public static string Код_Gisal {
            get {
                return ResourceManager.GetString("Код Gisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код линии.
        /// </summary>
        public static string Код_линии {
            get {
                return ResourceManager.GetString("Код линии", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код машины.
        /// </summary>
        public static string Код_машины {
            get {
                return ResourceManager.GetString("Код машины", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код поставщика Gisal.
        /// </summary>
        public static string Код_поставщика_Gisal {
            get {
                return ResourceManager.GetString("Код поставщика Gisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string Количество {
            get {
                return ResourceManager.GetString("Количество", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать.
        /// </summary>
        public static string Копировать {
            get {
                return ResourceManager.GetString("Копировать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копия заказа.
        /// </summary>
        public static string Копия_заказа {
            get {
                return ResourceManager.GetString("Копия заказа", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наблюдатель.
        /// </summary>
        public static string Наблюдатель {
            get {
                return ResourceManager.GetString("Наблюдатель", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование заказа.
        /// </summary>
        public static string Наименование_заказа {
            get {
                return ResourceManager.GetString("Наименование заказа", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string Нет {
            get {
                return ResourceManager.GetString("Нет", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет изменений в карточке.
        /// </summary>
        public static string Нет_изменений_в_карточке {
            get {
                return ResourceManager.GetString("Нет изменений в карточке", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № модуля.
        /// </summary>
        public static string Номер_модуля {
            get {
                return ResourceManager.GetString("Номер модуля", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общее количество файлов не должно превышать 5шт.
        /// </summary>
        public static string Общее_количество_файлов_не_должно_превышать_5шт {
            get {
                return ResourceManager.GetString("Общее количество файлов не должно превышать 5шт", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обычный.
        /// </summary>
        public static string Обычный {
            get {
                return ResourceManager.GetString("Обычный", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Один специальный символ, по крайней мере.
        /// </summary>
        public static string Один_специальный_символ__по_крайней_мере {
            get {
                return ResourceManager.GetString("Один специальный символ, по крайней мере", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одну заглавную букву, по крайней мере.
        /// </summary>
        public static string Одну_заглавную_букву__по_крайней_мере {
            get {
                return ResourceManager.GetString("Одну заглавную букву, по крайней мере", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одну прописную букву, по крайней мере.
        /// </summary>
        public static string Одну_прописную_букву__по_крайней_мере {
            get {
                return ResourceManager.GetString("Одну прописную букву, по крайней мере", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одну цифру, по крайней мере.
        /// </summary>
        public static string Одну_цифру__по_крайней_мере {
            get {
                return ResourceManager.GetString("Одну цифру, по крайней мере", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор.
        /// </summary>
        public static string Оператор {
            get {
                return ResourceManager.GetString("Оператор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string Описание {
            get {
                return ResourceManager.GetString("Описание", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Отмена {
            get {
                return ResourceManager.GetString("Отмена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить заказ.
        /// </summary>
        public static string Отменить_заказ {
            get {
                return ResourceManager.GetString("Отменить заказ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить SMS.
        /// </summary>
        public static string Отправить_SMS {
            get {
                return ResourceManager.GetString("Отправить SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить загруженные файлы.
        /// </summary>
        public static string Очистить_загруженные_файлы {
            get {
                return ResourceManager.GetString("Очистить загруженные файлы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не совпадают.
        /// </summary>
        public static string Пароли_не_совпадают {
            get {
                return ResourceManager.GetString("Пароли не совпадают", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Пароль {
            get {
                return ResourceManager.GetString("Пароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль должен.
        /// </summary>
        public static string Пароль_должен {
            get {
                return ResourceManager.GetString("Пароль должен", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль слишком прост.
        /// </summary>
        public static string Пароль_слишком_прост {
            get {
                return ResourceManager.GetString("Пароль слишком прост", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторить пароль.
        /// </summary>
        public static string Повторить_пароль {
            get {
                return ResourceManager.GetString("Повторить пароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение.
        /// </summary>
        public static string Подразделение {
            get {
                return ResourceManager.GetString("Подразделение", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение с таким именем уже существует в базе.
        /// </summary>
        public static string Подразделение_с_таким_именем_уже_существует_в_базе {
            get {
                return ResourceManager.GetString("Подразделение с таким именем уже существует в базе", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение успешно восстановлено.
        /// </summary>
        public static string Подразделение_успешно_восстановлено {
            get {
                return ResourceManager.GetString("Подразделение успешно восстановлено", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение успешно изменено.
        /// </summary>
        public static string Подразделение_успешно_изменено {
            get {
                return ResourceManager.GetString("Подразделение успешно изменено", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение успешно создано.
        /// </summary>
        public static string Подразделение_успешно_создано {
            get {
                return ResourceManager.GetString("Подразделение успешно создано", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение успешно удалено.
        /// </summary>
        public static string Подразделение_успешно_удалено {
            get {
                return ResourceManager.GetString("Подразделение успешно удалено", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение успешно удалено из базы.
        /// </summary>
        public static string Подразделение_успешно_удалено_из_базы {
            get {
                return ResourceManager.GetString("Подразделение успешно удалено из базы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделения.
        /// </summary>
        public static string Подразделения {
            get {
                return ResourceManager.GetString("Подразделения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждаю, данные введены верно.
        /// </summary>
        public static string Подтверждаю__данные_введены_верно {
            get {
                return ResourceManager.GetString("Подтверждаю, данные введены верно", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждаю отмену заказа.
        /// </summary>
        public static string Подтверждаю_отмену_заказа {
            get {
                return ResourceManager.GetString("Подтверждаю отмену заказа", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователи.
        /// </summary>
        public static string Пользователи {
            get {
                return ResourceManager.GetString("Пользователи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь не найден или не верен пароль.
        /// </summary>
        public static string Пользователь_не_найден_или_не_верен_пароль {
            get {
                return ResourceManager.GetString("Пользователь не найден или не верен пароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким именем уже существует в базе.
        /// </summary>
        public static string Пользователь_с_таким_именем_уже_существует_в_базе {
            get {
                return ResourceManager.GetString("Пользователь с таким именем уже существует в базе", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь удален.
        /// </summary>
        public static string Пользователь_удален {
            get {
                return ResourceManager.GetString("Пользователь удален", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь успешно восстановлен.
        /// </summary>
        public static string Пользователь_успешно_восстановлен {
            get {
                return ResourceManager.GetString("Пользователь успешно восстановлен", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь успешно изменен.
        /// </summary>
        public static string Пользователь_успешно_изменен {
            get {
                return ResourceManager.GetString("Пользователь успешно изменен", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь успешно создан.
        /// </summary>
        public static string Пользователь_успешно_создан {
            get {
                return ResourceManager.GetString("Пользователь успешно создан", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь успешно удален.
        /// </summary>
        public static string Пользователь_успешно_удален {
            get {
                return ResourceManager.GetString("Пользователь успешно удален", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь успешно удален из базы.
        /// </summary>
        public static string Пользователь_успешно_удален_из_базы {
            get {
                return ResourceManager.GetString("Пользователь успешно удален из базы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставщик.
        /// </summary>
        public static string Поставщик {
            get {
                return ResourceManager.GetString("Поставщик", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышено количество попыток продления даты поставки.
        /// </summary>
        public static string Превышено_количество_попыток_продления_даты_поставки {
            get {
                return ResourceManager.GetString("Превышено количество попыток продления даты поставки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание.
        /// </summary>
        public static string Примечание {
            get {
                return ResourceManager.GetString("Примечание", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотр.
        /// </summary>
        public static string Просмотр {
            get {
                return ResourceManager.GetString("Просмотр", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разработчик.
        /// </summary>
        public static string Разработчик {
            get {
                return ResourceManager.GetString("Разработчик", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование.
        /// </summary>
        public static string Редактирование {
            get {
                return ResourceManager.GetString("Редактирование", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роль.
        /// </summary>
        public static string Роль {
            get {
                return ResourceManager.GetString("Роль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить счетчик продления даты поставки.
        /// </summary>
        public static string Сбросить_счетчик_продления_даты_поставки {
            get {
                return ResourceManager.GetString("Сбросить счетчик продления даты поставки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать.
        /// </summary>
        public static string Скачать {
            get {
                return ResourceManager.GetString("Скачать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать все.
        /// </summary>
        public static string Скачать_все {
            get {
                return ResourceManager.GetString("Скачать все", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать все файлы.
        /// </summary>
        public static string Скачать_все_файлы {
            get {
                return ResourceManager.GetString("Скачать все файлы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена пароля.
        /// </summary>
        public static string Смена_пароля {
            get {
                return ResourceManager.GetString("Смена пароля", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение.
        /// </summary>
        public static string Сообщение {
            get {
                return ResourceManager.GetString("Сообщение", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сопроводительные документы.
        /// </summary>
        public static string Сопроводительные_документы {
            get {
                return ResourceManager.GetString("Сопроводительные документы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Сохранить {
            get {
                return ResourceManager.GetString("Сохранить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        public static string Справка {
            get {
                return ResourceManager.GetString("Справка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срочность.
        /// </summary>
        public static string Срочность {
            get {
                return ResourceManager.GetString("Срочность", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срочный.
        /// </summary>
        public static string Срочный {
            get {
                return ResourceManager.GetString("Срочный", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string Статус {
            get {
                return ResourceManager.GetString("Статус", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление файла выполнено успешно.
        /// </summary>
        public static string Удаление_файла_выполнено_успешно {
            get {
                return ResourceManager.GetString("Удаление файла выполнено успешно", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалённые.
        /// </summary>
        public static string Удалённые {
            get {
                return ResourceManager.GetString("Удалённые", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Удалить {
            get {
                return ResourceManager.GetString("Удалить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалять файлы может только администратор.
        /// </summary>
        public static string Удалять_файлы_может_только_администратор {
            get {
                return ResourceManager.GetString("Удалять файлы может только администратор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл или общее количество файлов не должно превышать 5мб.
        /// </summary>
        public static string Файл_или_общее_количество_файлов_не_должно_превышать_5мб {
            get {
                return ResourceManager.GetString("Файл или общее количество файлов не должно превышать 5мб", resourceCulture);
            }
        }
    }
}
